### PR TITLE
week 5

### PR DESCRIPTION
**Pull request by nkechiagbogo**

### CODE REVIEW

**Review by emetowinner — CHANGES_REQUESTED** [review]
Please I can't accept this pull request, it seems you copied peoples work too, and am seeing files that belongs to other fellows within your own pull request.

**Comment by nkechiagbogo** [comment]
Hi Mr Winner,  thank you for your feedback, what do you advice I do?

Regards.
Nkechi Ijeoma.

**Comment by emetowinner** [comment]
Call me after the demo today.

**Comment by nkechiagbogo** [comment]
Good morning Mr Winner,
 Okay.thank you.

Regards
Nkechi Ijeoma

**Pull request closed without merging**
